[project]
name = "newqfe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bokeh>=3.1.0",
    "dask>=2025.9.1",
    "distributed>=2025.9.1",
    "graphviz>=0.21",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "scipy>=1.16.2",
]
